# Generated by Django 4.2 on 2025-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookreservation", "0002_bookreservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreservation",
            name="bookid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookreservation",
            name="studentid",
            field=models.IntegerField(default=0),
        ),
    ]
